# Dictionaries

In [1]:
arr = [1, 2, 3, "ian", 4, 5, "beth", 6, "camila", 7, 8, 9, 10, "adrian"]

In [2]:
print(arr)

[1, 2, 3, 'ian', 4, 5, 'beth', 6, 'camila', 7, 8, 9, 10, 'adrian']


In [3]:
d = {} # My first dictionary!
d["camila"] = ["An awesome student in IDS 301", 3]
d["chair"] = "Something we sit on"
d[8] = "A number"
print(d["camila"])
print(d.keys())

['An awesome student in IDS 301', 3]
dict_keys(['camila', 'chair', 8])


In [4]:
"beth" in d

False

In [5]:
import json
tweets = json.load(open("tweets_01-08-2021.json", "r"))
first = tweets[0]
print(first.keys())
print(len(tweets)/(10*365))

first["retweets"]

dict_keys(['id', 'text', 'isRetweet', 'isDeleted', 'device', 'favorites', 'retweets', 'date', 'isFlagged'])
15.498904109589041


255

In [15]:
def get_counts(tweets):
    counts = {} # key = word, value = counts of that word
    i = 0
    while i < len(tweets):
        tweet = tweets[i]
        words = tweet["text"].split()
        for j in range(len(words)):
            w = words[j].lower()
            if w not in counts: # First time we're seeing the word
                counts[w] = 1
            else:
                counts[w] += 1
        i += 1
    return counts

counts = get_counts(tweets)

words = list(counts.keys())
words_counts = list(counts.values())

print(words[0], words_counts[0])

republicans 545


In [8]:
print(tweets[-1]["favorites"])

95169


In [2]:
## Months final, for the plot_coronavirus_timeline function
MONTHS = {'Jan':'01', 'Feb':'02', 'Mar':'03', 'Apr':'04', 'May':'05', 'Jun':'06', 'Jul':'07', 'Aug':'08', 'Sep':'09', 'Oct':'10', 'Nov':'11', 'Dec':'12'}

def get_tweet_date(tweet):
    year = ""
    month = ""
    day = ""
    if "created_at" in tweet:
        date = tweet['created_at']
        # Separate out date into components in a list
        # Each element is a different component separated
        # by a space
        fields = date.split() 
        
        # The year is the last field
        year = fields[-1]
        
        # Use the dictionary defined at the top of the file
        # to convert from a three letter month to a two digit month
        month = MONTHS[fields[1]] 

        # This magic code formats a day to be 2 digits, potentially
        # with a leading zero
        day = "%02d"%int(fields[2]) 
    elif "date" in tweet:
        date = tweet["date"].split()[0]
        year, month, day = date.split("-")
    return "{}/{} {}".format(month, day, year)

In [4]:
get_tweet_date(tweets[0])

'08/02 2011'

In [7]:
# What's the most popular tweet?
def get_most_popular(tweets, key):
    max_idx = 0 # Index of the tweet with the most retweets
    for i in range(1, len(tweets)):
        # If tweets[i] has more retweets than tweets[max_idx]
        #      then max_idx = i
        if tweets[i][key] > tweets[max_idx][key]:
            max_idx = i
    return tweets[max_idx]

print(get_most_popular(tweets, "retweets"))

{'id': 1311892190680014800, 'text': 'Tonight, @FLOTUS and I tested positive for COVID-19. We will begin our quarantine and recovery process immediately. We will get through this TOGETHER!', 'isRetweet': 'f', 'isDeleted': 'f', 'device': 'Twitter for iPhone', 'favorites': 1869706, 'retweets': 408866, 'date': '2020-10-02 04:54:06', 'isFlagged': 'f'}


In [11]:
# Count how many times Trump uses different devices
def count_device_use(tweets):
    counts = {} # Key is device string (e.g. "IPhone")
    # Value is the count of # of tweets that used that device
    
    for i in range(len(tweets)):
        tweet = tweets[i]
        if tweet["isRetweet"] == "f":
            device = tweet["device"]
            if not device in counts:
                counts[device] = 0 # Create an entry for a new device
            counts[device] = counts[device] + 1
    return counts

counts = count_device_use(tweets)
print("len(counts)", len(counts))
print("len(tweets)", len(tweets))

sum_all_devices = 0 # Accumulator variable
for key in counts.keys():
    # Sum up the counts across all devices
    sum_all_devices += counts[key]
print("sum_all_devices", sum_all_devices)

len(counts) 20
len(tweets) 56571
sum_all_devices 46694


In [21]:
chars = [chr(ord('a')+i) for i in range(26)] + list(range(10))
print(chars)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [25]:
def filter_alphanumeric(s):
    chars = [chr(ord('a')+i) for i in range(26)] + list(range(10)) + ["/", "@", "#"]
    chars = set(chars)
    filtered = [c for c in s if c in chars]
    return "".join(filtered)

'@adrian'

In [26]:



words = tweets[0]["text"].split()
for i in range(len(words)):
    words[i] = words[i].lower()
    words[i] = filter_alphanumeric(words[i])
print(words)

['republicans', 'and', 'democrats', 'have', 'both', 'created', 'our', 'economic', 'problems']


In [28]:
def get_most_common_word(tweets):
    counts = {} # key = word, value = counts of that word
    i = 0
    while i < len(tweets):
        tweet = tweets[i]
        words = tweet["text"].split()
        for j in range(len(words)):
            w = words[j].lower()
            w = filter_alphanumeric(w)
            if w not in counts: # First time we're seeing the word
                counts[w] = 1
            else:
                counts[w] += 1
        i += 1
    return counts

counts = get_most_common_word(tweets)

In [37]:
for example in ["biden", "@realdonaldtrump", "covfefe", "lies", "fake", "news"]:
    print(example, counts[example])

biden 982
@realdonaldtrump 10918
covfefe 2
lies 206
fake 1282
news 1839


In [40]:
max_word = "biden"
for word in counts:
    if counts[word] > counts[max_word]:
        max_word = word
print(max_word, counts[max_word])

the 45868


In [48]:
import numpy as np

words = list(counts.keys())
words_count = list(counts.values())
idx = np.argmax(words_count) # *Index* in words_count of the maximum value
print(words[idx])

the


In [9]:
# When do the tweets spike?

# Any days where there weren't any tweets?
# Standard deviation of number of tweet/day

# Any tone changes in tweets?

# Days of the week or time of day when tweets spike

In [24]:
import numpy as np
cols = 5
x = np.arange(cols)+1
x = np.reshape(x, (1, cols))
print(x)

A = np.random.rand(4, cols)
print(A)

print(A / x)

[[1 2 3 4 5]]
[[0.96565636 0.89031888 0.8031215  0.09507713 0.17573712]
 [0.49127305 0.4710882  0.6827037  0.64401631 0.20167903]
 [0.77145634 0.18031273 0.084909   0.58742981 0.78609396]
 [0.29006986 0.49373889 0.5879348  0.05944346 0.39498147]]
[[0.96565636 0.44515944 0.26770717 0.02376928 0.03514742]
 [0.49127305 0.2355441  0.2275679  0.16100408 0.04033581]
 [0.77145634 0.09015636 0.028303   0.14685745 0.15721879]
 [0.29006986 0.24686944 0.19597827 0.01486087 0.07899629]]
